name: Update blocklist ipset
on:
  schedule:
    - cron: '0 0,12 * * *'    # runs at 00:00 and 12:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-ipset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download blocklist
        run: |
          curl -fsSL -o prod_ad_data-shield_ipv4_blocklist.ipset "https://raw.githubusercontent.com/duggytuxy/Data-Shield_IPv4_Blocklist/main/prod_ad_data-shield_ipv4_blocklist.txt"

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet --exit-code -- prod_ad_data-shield_ipv4_blocklist.ipset; then
            echo "No changes to commit"
          else
            git add prod_ad_data-shield_ipv4_blocklist.ipset
            git commit -m "Update blocklist ipset: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push
          fi
