name: Update upstream level 2 to ipset
on:
  schedule:
    - cron: '0 0,12 * * *'    # runs at 00:00 and 12:00 UTC daily (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

env:
  RAW_URL: "https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/2.txt"
  TARGET_FILE: levels-2.ipset

jobs:
  update-level2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download upstream to temp file
        run: |
          set -euo pipefail
          echo "Fetching $RAW_URL"
          TMPFILE="$(mktemp)"
          curl -fsSL "$RAW_URL" -o "$TMPFILE"
          echo "Downloaded to $TMPFILE — size: $(stat -c%s "$TMPFILE") bytes — lines: $(wc -l < "$TMPFILE")"

      - name: Compare and replace if different
        run: |
          set -euo pipefail
          # TMPFILE is created in previous step
          if [ ! -f "$TMPFILE" ]; then
            echo "Temp file missing, aborting" >&2
            exit 1
          fi
          TARGET="${TARGET_FILE}"
          if [ ! -f "$TARGET" ]; then
            mv "$TMPFILE" "$TARGET"
            echo "Target did not exist — moved downloaded file into place"
          else
            if cmp -s "$TMPFILE" "$TARGET"; then
              echo "Downloaded file is identical to $TARGET — no update"
              rm -f "$TMPFILE"
              exit 0
            else
              mv "$TMPFILE" "$TARGET"
              echo "Downloaded file differed — replaced $TARGET"
            fi
          fi

      - name: Show head of target file
        run: |
          echo "--- head of $TARGET_FILE ---"
          head -n 8 "$TARGET_FILE" || true

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet --exit-code -- "$TARGET_FILE"; then
            echo "No changes to commit"
          else
            git add "$TARGET_FILE"
            git commit -m "Update level 2 ipset: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push origin HEAD:main
          fi
